### ISSUE TITLE
Any chance the source to the iOS plugin can also be shared, as the file path for the recorded video is not accessible

### ISSUE THREAD

**Issue by SimonDarksideJ** [keijiro/VideoWriterTest#3]
Always an admirer of your work and your ultimate honesty in sharing your work, a model I always try to live by.

In this case, the source for the iOS plugin itself isn't shared as it would be great to extend it with additional properties, such as the filepath to the recorded video.

I have been on the hunt for a bridge to the iOS and Android video encoding libraries for a while and this project finally gave me hope.

Thanks @keijiro

**Comment by keijiro** [comment]
It's available in the `Plugin` directory.
